In [1]:
# is it a lotte choco pie? or numerical python

In [2]:
x = 2
y = 3*x**2
y_ = 6*x  

In [3]:
y

12

In [4]:
y_

12

In [17]:
y = (9*x + 7)**2

In [18]:
y_ = 18*(9*x + 7)

In [19]:
y

625

In [20]:
y_

450

In [23]:
(y-y_)/y

0.28

In [26]:
# Numpy
import numpy as np

In [27]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])

In [28]:
a.dot(b)

55

In [29]:
1 + 4 + 9 + 16 + 25

55

In [31]:
np.sum(a)

15

In [32]:
x = np.array([[1, 2], 
              [3, 4]])
y = np.array([[4, 7],
              [3, 7]])


In [33]:
np.sum(x)

10

In [34]:
np.sum(x, axis = 0 )

array([4, 6])

In [35]:
np.sum(x, axis = 1 )

array([3, 7])

In [36]:
np.sum(y, axis = 0)

array([ 7, 14])

In [37]:
np.sum(y, axis = 1)

array([11, 10])

In [38]:
a 

array([1, 2, 3, 4, 5])

In [41]:
# b = a**2
b

array([ 1,  4,  9, 16, 25])

In [40]:
np.stack((a, b), axis = 0)

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [49]:
np.stack((x, y), axis = 0)

array([[[1, 2],
        [3, 4]],

       [[4, 7],
        [3, 7]]])

In [50]:
np.stack((x, y), axis = 1)

array([[[1, 2],
        [4, 7]],

       [[3, 4],
        [3, 7]]])

In [51]:
a

array([1, 2, 3, 4, 5])

In [52]:
x

array([[1, 2],
       [3, 4]])

In [53]:
rn_mat = np.random.random((8, 3))

In [54]:
rn_mat

array([[0.96898703, 0.26808651, 0.92976822],
       [0.09963769, 0.48366771, 0.70414833],
       [0.32500405, 0.86114903, 0.37352927],
       [0.19736685, 0.13308594, 0.99768264],
       [0.10296421, 0.81396798, 0.49374526],
       [0.55420111, 0.57926995, 0.9244585 ],
       [0.65845571, 0.97551635, 0.19826641],
       [0.60456813, 0.24194581, 0.76627421]])

In [55]:
rn_mat_transpose = rn_mat.T

In [60]:
rn_mat_transpose

array([[0.96898703, 0.09963769, 0.32500405, 0.19736685, 0.10296421,
        0.55420111, 0.65845571, 0.60456813],
       [0.26808651, 0.48366771, 0.86114903, 0.13308594, 0.81396798,
        0.57926995, 0.97551635, 0.24194581],
       [0.92976822, 0.70414833, 0.37352927, 0.99768264, 0.49374526,
        0.9244585 , 0.19826641, 0.76627421]])

In [63]:
# rn_mat_reshape = rn_mat.reshape((3, 8))
rn_mat

array([[0.96898703, 0.26808651, 0.92976822],
       [0.09963769, 0.48366771, 0.70414833],
       [0.32500405, 0.86114903, 0.37352927],
       [0.19736685, 0.13308594, 0.99768264],
       [0.10296421, 0.81396798, 0.49374526],
       [0.55420111, 0.57926995, 0.9244585 ],
       [0.65845571, 0.97551635, 0.19826641],
       [0.60456813, 0.24194581, 0.76627421]])

In [62]:
rn_mat_reshape

array([[0.96898703, 0.26808651, 0.92976822, 0.09963769, 0.48366771,
        0.70414833, 0.32500405, 0.86114903],
       [0.37352927, 0.19736685, 0.13308594, 0.99768264, 0.10296421,
        0.81396798, 0.49374526, 0.55420111],
       [0.57926995, 0.9244585 , 0.65845571, 0.97551635, 0.19826641,
        0.60456813, 0.24194581, 0.76627421]])