In [1]:
import numpy as np

In [2]:
# !pip install numpy

In [10]:
a = np.array([1, 2, 3, 4, 5])

In [11]:
type(a)
a

array([1, 2, 3, 4, 5])

In [7]:
a.shape  #  (anyvalue, ) it will treat it as a vector 

(5,)

In [13]:
a = np.array([[1], [2], [3], [4], [5]])

In [14]:
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [15]:
a.shape

(5, 1)

In [21]:
np.zeros((4, 5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np.full((2, 2), 3)

array([[3, 3],
       [3, 3]])

In [30]:
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [43]:
rn_mat = np.random.random((3, 5))   # [0, 1)

In [44]:
rn_mat

array([[0.71064201, 0.1225293 , 0.89792625, 0.56920914, 0.77912462],
       [0.14407405, 0.86033523, 0.83433423, 0.38185245, 0.43790274],
       [0.95440972, 0.03646113, 0.91004792, 0.21624669, 0.8104309 ]])

In [45]:
rn_mat.shape

(3, 5)

In [46]:
rn_mat[0]

array([0.71064201, 0.1225293 , 0.89792625, 0.56920914, 0.77912462])

In [47]:
rn_mat[1]

array([0.14407405, 0.86033523, 0.83433423, 0.38185245, 0.43790274])

In [48]:
rn_mat[2]

array([0.95440972, 0.03646113, 0.91004792, 0.21624669, 0.8104309 ])

In [50]:
rn_mat

array([[0.71064201, 0.1225293 , 0.89792625, 0.56920914, 0.77912462],
       [0.14407405, 0.86033523, 0.83433423, 0.38185245, 0.43790274],
       [0.95440972, 0.03646113, 0.91004792, 0.21624669, 0.8104309 ]])

In [52]:
rn_mat[1, 2]  # ((0, 1, 2) -> row and (0, 1, 2, 3, 4) -> columns)

0.8343342292420048

In [53]:
rn_mat[0, 0]

0.7106420103011762

In [54]:
rn_mat[2, 3]

0.2162466948431203

In [55]:
rn_mat[1, 4]

0.4379027429065123

In [59]:
rn_mat = np.random.random((6, 5))

In [60]:
rn_mat

array([[0.86452255, 0.42226857, 0.77947688, 0.73063587, 0.28223432],
       [0.03957213, 0.48490841, 0.37674442, 0.96544211, 0.30373912],
       [0.40991229, 0.09026695, 0.28907344, 0.84756442, 0.65847718],
       [0.39777966, 0.26615392, 0.48405352, 0.65735825, 0.39439432],
       [0.01902332, 0.75205992, 0.70916817, 0.33276012, 0.51899016],
       [0.2935698 , 0.50731983, 0.94767596, 0.52008369, 0.16966858]])

In [61]:
rn_mat[1:3, : 5]

array([[0.03957213, 0.48490841, 0.37674442, 0.96544211, 0.30373912],
       [0.40991229, 0.09026695, 0.28907344, 0.84756442, 0.65847718]])

In [64]:
idx = [0, 1]
rn_mat[ : , idx ]

array([[0.86452255, 0.42226857],
       [0.03957213, 0.48490841],
       [0.40991229, 0.09026695],
       [0.39777966, 0.26615392],
       [0.01902332, 0.75205992],
       [0.2935698 , 0.50731983]])

In [63]:
rn_mat[ : , : 2]

array([[0.86452255, 0.42226857],
       [0.03957213, 0.48490841],
       [0.40991229, 0.09026695],
       [0.39777966, 0.26615392],
       [0.01902332, 0.75205992],
       [0.2935698 , 0.50731983]])

In [65]:
rn_mat.shape

(6, 5)

In [68]:
rn_mat[3:5, 2:4]

array([[0.48405352, 0.65735825],
       [0.70916817, 0.33276012]])

In [76]:
rn_mat[ : , 4:].shape

(6, 1)

In [77]:
rn_mat[-1]

array([0.2935698 , 0.50731983, 0.94767596, 0.52008369, 0.16966858])

In [78]:
x = np.array([[1, 2], 
              [3, 4]])
y = np.array([[4, 7],
              [3, 7]])


In [79]:
x + y

array([[ 5,  9],
       [ 6, 11]])

In [80]:
x - y

array([[-3, -5],
       [ 0, -3]])

In [81]:
x * y

array([[ 4, 14],
       [ 9, 28]])

In [82]:
x/y

array([[0.25      , 0.28571429],
       [1.        , 0.57142857]])

In [83]:
np.add(x, y)

array([[ 5,  9],
       [ 6, 11]])

In [84]:
np.subtract(x, y)

array([[-3, -5],
       [ 0, -3]])

In [85]:
np.subtract(y, x)

array([[3, 5],
       [0, 3]])

In [86]:
np.multiply(x, y)

array([[ 4, 14],
       [ 9, 28]])

In [87]:
np.divide(x, y)

array([[0.25      , 0.28571429],
       [1.        , 0.57142857]])

In [88]:
np.divide(y, x)

array([[4.  , 3.5 ],
       [1.  , 1.75]])

In [92]:
np.sqrt(289)

17.0

In [93]:
np.matmul(x, y)

array([[10, 21],
       [24, 49]])

In [94]:
np.dot(x, y)

array([[10, 21],
       [24, 49]])

In [95]:
x@y

array([[10, 21],
       [24, 49]])