In [1]:
import numpy as np

In [2]:
np.full((3,5), 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [6]:
a = np.array([1, 2, 3, 4])  # Vector
print(a.shape)
b = np.array([[1, 2, 3, 4]])
print(b.shape)

(4,)
(1, 4)


In [11]:
np.array([[1,2,3,4],
          [1,2,3,5]]).shape

(2, 4)

In [12]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.eye(4)  # indentity 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
rn_mat = np.random.random((3, 2))

In [8]:
rn_mat

array([[0.02251503, 0.05911925],
       [0.95104977, 0.10133724],
       [0.77441806, 0.45795191]])

In [10]:
rn_mat[0, 1]

0.05911925031518761

In [9]:
rn_mat[ 0 : , 1]

array([0.05911925, 0.10133724, 0.45795191])

In [26]:
rn_mat

array([[0.37011606, 0.82470595],
       [0.88661336, 0.35418034],
       [0.54537234, 0.79427171]])

In [31]:
rn_mat[1, 0] == rn_mat[1, :1]

array([ True])

In [32]:
x = np.array([[1, 2], 
              [3, 4]])
y = np.array([[4, 7], 
              [3, 7]])
print(x.shape, y.shape)

(2, 2) (2, 2)


In [34]:
x+y, x-y, x*y, x/y

(array([[ 5,  9],
        [ 6, 11]]),
 array([[-3, -5],
        [ 0, -3]]),
 array([[ 4, 14],
        [ 9, 28]]),
 array([[0.25      , 0.28571429],
        [1.        , 0.57142857]]))

In [37]:
np.add(x, y),np.subtract(x, y), np.multiply(x, y), np.divide(x, y)

(array([[ 5,  9],
        [ 6, 11]]),
 array([[-3, -5],
        [ 0, -3]]),
 array([[ 4, 14],
        [ 9, 28]]),
 array([[0.25      , 0.28571429],
        [1.        , 0.57142857]]))

In [39]:
np.sqrt(144)

12.0

In [40]:
x

array([[1, 2],
       [3, 4]])

In [41]:
y

array([[4, 7],
       [3, 7]])

In [44]:
np.dot(x,y)

array([[10, 21],
       [24, 49]])

In [45]:
np.dot(y, x)

array([[25, 36],
       [24, 34]])

In [46]:
# x dot y does not equal to y dot x

In [49]:
np.matmul(x, y)

array([[10, 21],
       [24, 49]])

In [50]:
np.matmul(y, x)

array([[25, 36],
       [24, 34]])

In [51]:
x.dot(y)

array([[10, 21],
       [24, 49]])

In [52]:
y.dot(x)

array([[25, 36],
       [24, 34]])

In [59]:
a = np.array([[1, 2, 3, 4, 5]])
a.shape

(1, 5)

In [64]:
np.sum(a, axis = 0)  # axis = 0 operation row wise
np.sum(a, axis = 1)  # axis = 1 operation col. wise

array([15])

In [62]:
x

array([[1, 2],
       [3, 4]])

In [63]:
np.sum(x)

10

In [65]:
np.sum(x, axis = 0) 

array([4, 6])

In [66]:
np.sum(x, axis = 1)

array([3, 7])

In [67]:
# Stacking 

In [68]:
a

array([[1, 2, 3, 4, 5]])

In [69]:
b = a**2

In [70]:
b

array([[ 1,  4,  9, 16, 25]])

In [77]:
np.stack((a, b), axis = 0)

array([[[ 1,  2,  3,  4,  5]],

       [[ 1,  4,  9, 16, 25]]])

In [76]:
np.stack((a, b), axis = 1)

array([[[ 1,  2,  3,  4,  5],
        [ 1,  4,  9, 16, 25]]])

In [79]:
a = np.array([[1, 2],
             [4, 4]])
b = np.array([[1, 4], 
              [16, 16]])

In [80]:
np.stack((a, b), axis = 0)

array([[[ 1,  2],
        [ 4,  4]],

       [[ 1,  4],
        [16, 16]]])

In [81]:
np.stack((a, b), axis = 1)

array([[[ 1,  2],
        [ 1,  4]],

       [[ 4,  4],
        [16, 16]]])

In [90]:
rn_mat.T  # it will loose the continuity 

array([[0.37011606, 0.88661336, 0.54537234],
       [0.82470595, 0.35418034, 0.79427171]])

In [88]:
np.transpose(rn_mat).shape

(2, 3)

In [91]:
# i don't want to loose my continuity for that we can use reshape function function

In [13]:
rn_mat

array([[0.02251503, 0.05911925],
       [0.95104977, 0.10133724],
       [0.77441806, 0.45795191]])

In [94]:
rn_mat.reshape((2, 3))

array([[0.37011606, 0.82470595, 0.88661336],
       [0.35418034, 0.54537234, 0.79427171]])

In [96]:
rn_mat.reshape((1, 6))

array([[0.37011606, 0.82470595, 0.88661336, 0.35418034, 0.54537234,
        0.79427171]])

In [97]:
a = np.random.random((4, 8))

In [98]:
a.shape

(4, 8)

In [100]:
a.reshape((2, -1)).shape

(2, 16)

In [103]:
a.reshape((-1, 4)).shape

(8, 4)

In [104]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
A = np.arange(-1, 20, step = 2)
A

array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [112]:
np.random.shuffle(A)

In [126]:
A

array([ 9, 13, 15,  5, 19, -1,  1,  3, 11, 17,  7])

In [3]:
np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method

In [12]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method

In [8]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [128]:
np.random.randint(-9, -7, 4) # for integers only

array([-8, -8, -9, -8])

In [13]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [9]:
np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method

In [134]:
# np.mean()
# np.median()
# np.var()
# np.std()
# np.average()

# Pandas : 

In [136]:
import pandas as pd

In [137]:
!pip install pandas

In [234]:
user_data = {
    'Marks_A' : np.random.randint(50, 100, 8),
    'Marks_B' : np.random.randint(50, 100, 8),
    'Marks_C' : np.random.randint(50, 100, 8)
}

In [235]:
user_data

{'Marks_A': array([93, 98, 75, 85, 96, 95, 81, 78]),
 'Marks_B': array([60, 95, 81, 97, 95, 52, 61, 50]),
 'Marks_C': array([86, 66, 85, 54, 65, 54, 52, 70])}

In [236]:
df = pd.DataFrame(user_data)

In [237]:
df

Marks_A  Marks_B  Marks_C
0       93       60       86
1       98       95       66
2       75       81       85
3       85       97       54
4       96       95       65
5       95       52       54
6       81       61       52
7       78       50       70

In [238]:
df.shape

(8, 3)

In [239]:
df.head() # first five rows

Marks_A  Marks_B  Marks_C
0       93       60       86
1       98       95       66
2       75       81       85
3       85       97       54
4       96       95       65

In [240]:
# df = df.to_excel('marks.xlsx')

In [241]:
df

Marks_A  Marks_B  Marks_C
0       93       60       86
1       98       95       66
2       75       81       85
3       85       97       54
4       96       95       65
5       95       52       54
6       81       61       52
7       78       50       70

In [242]:
df.columns

Index(['Marks_A', 'Marks_B', 'Marks_C'], dtype='object')

In [217]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Marks_A  8 non-null      int32
 1   Marks_B  8 non-null      int32
 2   Marks_C  8 non-null      int32
dtypes: int32(3)
memory usage: 228.0 bytes


In [243]:
# df.drop(columns=['Marks_A'], inplace=True)

In [244]:
df

Marks_A  Marks_B  Marks_C
0       93       60       86
1       98       95       66
2       75       81       85
3       85       97       54
4       96       95       65
5       95       52       54
6       81       61       52
7       78       50       70

In [245]:
df.iloc[:4, 1] # index or integer locator

0    60
1    95
2    81
3    97
Name: Marks_B, dtype: int32

In [246]:
df.iloc[:5, :2]

Marks_A  Marks_B
0       93       60
1       98       95
2       75       81
3       85       97
4       96       95

In [250]:
df.iloc[:5, 1:3 ]

Marks_B  Marks_C
0       60       86
1       95       66
2       81       85
3       97       54
4       95       65

In [254]:
df.iloc[  : , [0, 2]]

Marks_A  Marks_C
0       93       86
1       98       66
2       75       85
3       85       54
4       96       65
5       95       54
6       81       52
7       78       70

In [257]:
idx = df.columns.get_loc('Marks_C')

In [258]:
idx

2

In [263]:
idx = [df.columns.get_loc('Marks_C'), df.columns.get_loc('Marks_A')]

In [264]:
idx

[2, 0]

In [265]:
df.iloc[:5, idx]

Marks_C  Marks_A
0       86       93
1       66       98
2       85       75
3       54       85
4       65       96

In [276]:
df.sort_values(by=['Marks_B'])

Marks_A  Marks_B  Marks_C
7       78       50       70
5       95       52       54
0       93       60       86
6       81       61       52
2       75       81       85
1       98       95       66
4       96       95       65
3       85       97       54

In [271]:
df

Marks_A  Marks_B  Marks_C
0       93       60       86
1       98       95       66
2       75       81       85
3       85       97       54
4       96       95       65
5       95       52       54
6       81       61       52
7       78       50       70

In [277]:
# We want to change the pandas to numpy format

In [283]:
A = df.values

In [284]:
A

array([[93, 60, 86],
       [98, 95, 66],
       [75, 81, 85],
       [85, 97, 54],
       [96, 95, 65],
       [95, 52, 54],
       [81, 61, 52],
       [78, 50, 70]])

In [289]:
df = pd.DataFrame(A, columns= ['Marks_A', 'Marks_B', 'Marks_C'])

In [291]:
df.head()

Marks_A  Marks_B  Marks_C
0       93       60       86
1       98       95       66
2       75       81       85
3       85       97       54
4       96       95       65