In [1]:
import numpy as np

In [3]:
a = np.random.random((3, 6))

In [4]:
a

array([[0.21682606, 0.11442387, 0.00817217, 0.04055613, 0.01938665,
        0.81115619],
       [0.02117722, 0.49705392, 0.04017818, 0.09151039, 0.6213202 ,
        0.97567351],
       [0.02780879, 0.2436567 , 0.53693549, 0.62938881, 0.44540941,
        0.42189758]])

In [6]:
a = a.reshape((2, -1))

In [7]:
a.shape

(2, 9)

In [21]:
a = a.reshape((-1, 6))


In [10]:
a.shape

(3, 6)

In [11]:
(1 + 2+ 3+ 4+5)/5

3.0

In [12]:
np.mean(a)

0.3201406261129667

In [13]:
np.median(a)

0.2302413796183116

In [17]:
b = np.arange(0, 10, 1)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.mean(b)

4.5

In [18]:
np.median(b)

4.5

In [19]:
a.shape

(3, 6)

In [20]:
np.mean(a, axis = 0)

array([0.08860402, 0.28504483, 0.19509528, 0.25381844, 0.36203875,
       0.73624243])

In [22]:
np.mean(a, axis = 1)  # operation col.

array([0.20175351, 0.37448557, 0.3841828 ])

In [25]:
a = np.array([[1, 2],
              [3, 4]])

In [26]:
a.shape

(2, 2)

In [27]:
np.mean(a)

2.5

In [28]:
np.mean(a, axis = 0)

array([2., 3.])

In [29]:
np.mean(a, axis = 1)

array([1.5, 3.5])

In [33]:
(np.std(a))**2

1.2500000000000002

In [31]:
np.var(a)

1.25

In [34]:
import pandas as pd

In [36]:
df = pd.read_csv('Titanic-Dataset.csv')

In [37]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [38]:
df.shape

(891, 12)

In [40]:
df.head(7)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [42]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [44]:
df.duplicated().sum()

0

In [53]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [54]:
(891-177)

714

In [55]:
891-687

204

In [58]:
df.drop(columns='Cabin', inplace=True)

In [60]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [48]:
df['Age'].isnull().sum()

177

In [49]:
df['Age'].mean()

29.69911764705882

In [51]:
df['Age'][0] 

22.0

In [69]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [71]:
df['Age'].isnull().sum()

0

In [73]:
df[df['Age'] == 29.69911764705882]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex        Age  SibSp  Parch      Ticket     Fare Embarked  
5      male  29.699118      0      0      330877   8.4583        Q  
17     male  29.699118      0      0      244373  13.0000        S  
19   female  29.699118      0      0        2649   7.2250        C  
26     male  29.699118      0      0        2631   7.2250        C  
28   female  29.699118      0      0      330959   7.8792        Q  
..      ...        ...    ...    ...         ...      ...      ...  
859    male  29.699118      0      0        2629   7.2292        C  
863  female  29.699118      8      2    CA. 2343  69.5500        S  
868    male  29.699118      0      0      345777   9.5000        S  
878    male  29.699118      0      0      349217   7.8958        S  
888  female  29.699118      1      2  W./C. 6607  23.4500        S  

[177 rows x 11 columns]

In [74]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [79]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [83]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].value_counts().idxmax())

In [84]:
df['Embarked'].isnull().sum()

0

In [85]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [86]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [87]:
df.drop(columns = ['PassengerId', 'Name', 'Ticket'], inplace=True)

In [88]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [89]:
# slice it to get Fare and Embarked column