In [1]:
a = 'Tushar'


In [2]:
print(f"My name is {a}")

My name is Tushar


In [3]:
st = 'Dogs are loyal to humans'

In [5]:
st.count('s')

2

In [6]:
st.count('T')

0

In [7]:
st.replace('s', 'D')

'DogD are loyal to humanD'

In [8]:
st.replace('Dogs','T' )

'T are loyal to humans'

In [11]:
ord('a') 

97

In [15]:
chr(ord('A') + 32)

'a'

In [13]:
97-65

32

In [18]:
st.upper()

'DOGS ARE LOYAL TO HUMANS'

In [19]:
st.lower()

'dogs are loyal to humans'

In [20]:
# write a program to change the case of a string : dogs are loyal to humans

In [22]:
# slicing of string

In [23]:
st

'Dogs are loyal to humans'

In [24]:
st[0]

'D'

In [29]:
st[ :4]

'Dogs'

In [30]:
st[4:]

' are loyal to humans'

In [31]:
st

'Dogs are loyal to humans'

In [32]:
st.isalpha()

False

In [34]:
'A'.isalpha()

True

In [40]:
st.endswith('Dogs are loyal to humans')

True

In [41]:
st = st.lower()

In [42]:
st

'dogs are loyal to humans'

In [43]:
st.capitalize()

'Dogs are loyal to humans'

In [46]:
st.find('loyal')

10

In [49]:
st[::-1]

'snamuh ot layol era sgod'

# List

In [70]:
l = ['Tushar', 1,2,3.4, True, range(0, 5),[1,2,4,4.5]]

In [52]:
type(l)

list

In [53]:
l[0]

'Tushar'

In [56]:
l[4]

True

In [59]:
l[6][2]

4

In [60]:
# function 

In [61]:
# 56

In [66]:
l

['Tushar', 1, 2, 3.4, True, range(0, 5), [1, 2, 4, 4.5]]

In [71]:
l.append(56)  # add it in the last 

In [72]:
l

['Tushar', 1, 2, 3.4, True, range(0, 5), [1, 2, 4, 4.5], 56]

In [74]:
l.insert(1, 'Khitoliya')

In [75]:
l

['Tushar', 'Khitoliya', 1, 2, 3.4, True, range(0, 5), [1, 2, 4, 4.5], 56]

In [77]:
l.pop()

56

In [78]:
l

['Tushar', 'Khitoliya', 1, 2, 3.4, True, range(0, 5), [1, 2, 4, 4.5]]

In [79]:
l.pop(-3)

True

In [80]:
l

['Tushar', 'Khitoliya', 1, 2, 3.4, range(0, 5), [1, 2, 4, 4.5]]

In [82]:
l.pop(4)

range(0, 5)

In [83]:
l

['Tushar', 'Khitoliya', 1, 2, [1, 2, 4, 4.5]]

In [86]:
l.remove(2)

In [87]:
l

['Tushar', 'Khitoliya', 1, [1, 2, 4, 4.5]]

In [88]:
l.append(1)

In [89]:
l

['Tushar', 'Khitoliya', 1, [1, 2, 4, 4.5], 1]

In [90]:
l.remove(1)

In [91]:
l

['Tushar', 'Khitoliya', [1, 2, 4, 4.5], 1]

In [92]:
# write a progam to reverse the list : 

In [98]:
sorted(l[2], reverse=True)

[4.5, 4, 2, 1]

In [99]:
# Tuple 

In [108]:
tup = (2, 3,'tushar', [1,2,3])

In [109]:
tup = tup + (1,)

In [110]:
tup

(2, 3, 'tushar', [1, 2, 3], 1)

In [111]:
tup = list(tup)

In [112]:
type(tup)

list

In [113]:
tup.append('Hi')

In [114]:
tup

[2, 3, 'tushar', [1, 2, 3], 1, 'Hi']

In [116]:
tup = tuple(tup)
tup

(2, 3, 'tushar', [1, 2, 3], 1, 'Hi')

In [107]:
# Dictionary 

In [117]:
# pair : value

In [118]:
d = {
    'a' : 'first alphabet',
    'b' : 'Second alphabet',
    'c' : 45,
    'd' : {
        'Tushar' : 'Data Science',
        'Indu' : 'Data Science'
    },
    'e' : [1,2,3,4]
}

In [119]:
type(d)

dict

In [121]:
d.items()

dict_items([('a', 'first alphabet'), ('b', 'Second alphabet'), ('c', 45), ('d', {'Tushar': 'Data Science', 'Indu': 'Data Science'}), ('e', [1, 2, 3, 4])])

In [122]:
for i in d.items():
    print(i)

('a', 'first alphabet')
('b', 'Second alphabet')
('c', 45)
('d', {'Tushar': 'Data Science', 'Indu': 'Data Science'})
('e', [1, 2, 3, 4])


In [126]:
for i in d.items():
    print(i[0])  # to fetch all the keys

a
b
c
d
e


In [127]:
for i in d.items():
    print(i[1])  # to fetch their respective values

first alphabet
Second alphabet
45
{'Tushar': 'Data Science', 'Indu': 'Data Science'}
[1, 2, 3, 4]


In [129]:
for i in d.keys():
    print(i)

a
b
c
d
e


In [131]:
d.values()

dict_values(['first alphabet', 'Second alphabet', 45, {'Tushar': 'Data Science', 'Indu': 'Data Science'}, [1, 2, 3, 4]])

In [132]:
for i in d.values():
    print(i)

first alphabet
Second alphabet
45
{'Tushar': 'Data Science', 'Indu': 'Data Science'}
[1, 2, 3, 4]


In [133]:
d.get('a')

'first alphabet'

In [134]:
d

{'a': 'first alphabet',
 'b': 'Second alphabet',
 'c': 45,
 'd': {'Tushar': 'Data Science', 'Indu': 'Data Science'},
 'e': [1, 2, 3, 4]}

In [144]:
isinstance(d['e'], list)

True

In [139]:
d['d']

{'Tushar': 'Data Science', 'Indu': 'Data Science'}

In [143]:
# print the value which is only dict and list

In [141]:
for i in d.values():
    print(i)

first alphabet
Second alphabet
45
{'Tushar': 'Data Science', 'Indu': 'Data Science'}
[1, 2, 3, 4]


In [145]:
# CLass

In [153]:
class student:
    mentor = 'Tushar'  # attributes
    age = 34

In [154]:
student

__main__.student

In [155]:
a = student()

In [156]:
a   # Rachit 

In [157]:
a.mentor

'Tushar'

In [152]:
a.age

34

In [190]:
class student:
    mentor = 'Tushar'
    age = 34
    
    def hello(self,name_, age_):
        self.age = age_
        self.name = name_
        print(f"my name is {self.name} and i am {self.age}yr old")

In [191]:
a = student()

In [192]:
a.mentor

'Tushar'

In [193]:
a.age

34

In [194]:
a.hello('Rachit', 25)

my name is Rachit and i am 25yr old


In [201]:
class student:
    mentor = 'Tushar'
    age = 34
    name = None
    
    def __init__(self, name_person, age_person,mentor):
        self.name = name_person
        self.age = age_person
        self.mentor = mentor
        print(f"my name is {self.name} and i am {self.age}yr old my mentor is {self.mentor}")
    

    # def hello(self,name_, age_):
    #     self.age = age_
    #     self.name = name_
    #     print(f"my name is {self.name} and i am {self.age}yr old")

In [204]:
a = student('rachit', 25, 'Rachit')

my name is rachit and i am 25yr old my mentor is Rachit


In [205]:
b = student('Indu', 34, 'XYZ')

my name is Indu and i am 34yr old my mentor is XYZ


In [206]:
class car:
    def __init__(self, model, mileage):
        self.model = model
        self.mileage = mileage
        print(self.model, self.mileage)

    def __add__(self, other):
        return int(self.mileage) + int(other.mileage)

    def __eq__(self, other):
        return str(self.mileage) == str(other.mileage)

    def __str__(self):
        return "{} {}".format(self.model, self.mileage)

In [210]:
c1 = car('BMW', 10)
c2 = car('Audi', 8)
print(c1 == c2)

BMW 10
Audi 8
False


In [211]:
str(c2)

'Audi 8'

# Numpy : Whenever we want to do some mathematical operations or calculation

In [213]:
# !pip install numpy

In [216]:
import numpy as np

In [220]:
a = np.array([1,
              2,
              3,
              4,
              5])
b = np.array([[1, 2, 3, 4, 5]])

In [218]:
type(a)

numpy.ndarray

In [219]:
a.shape

(5,)

In [221]:
b.shape

(1, 5)

In [222]:
a = np.array([[1], 
              [2], 
              [3], 
              [4], 
              [5]])

In [223]:
a.shape

(5, 1)

In [233]:
a = np.zeros((4, 13) ,dtype = int)

In [234]:
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [235]:
a = np.ones((6, 2))

In [236]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [244]:
a = np.full((2,4), 5,  dtype = float)

In [245]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [247]:
a = np.eye(4)

In [248]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [249]:
# random values of any size or shape of matrix

In [268]:
a = np.random.random((5,4)) # [0 1)

In [269]:
a

array([[0.10856878, 0.04661071, 0.97873869, 0.75271645],
       [0.23878341, 0.38536439, 0.42220848, 0.19479423],
       [0.42592917, 0.68269873, 0.88942215, 0.07469963],
       [0.52467116, 0.52076652, 0.1437887 , 0.19347521],
       [0.27602032, 0.85740833, 0.83093406, 0.9944588 ]])

In [270]:
a[:2]

array([[0.10856878, 0.04661071, 0.97873869, 0.75271645],
       [0.23878341, 0.38536439, 0.42220848, 0.19479423]])

In [271]:
a[:2, :2]

array([[0.10856878, 0.04661071],
       [0.23878341, 0.38536439]])

In [272]:
a[3:, 1]

array([0.52076652, 0.85740833])